"""Compare a decoded shortcut's identifiers against the Jellycore fact dataset.

Run:
    uv run python scripts/coverage_report.py samples/dictionary.shortcut

Writes a markdown report to `docs/coverage_<sample>.md` and prints a summary.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from shortcut_lib.decode import decode_file

REPO = Path(__file__).resolve().parent.parent
FACTS = REPO / "data/jellycore_facts.json"
DOC_DIR = REPO / "docs"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sample", type=Path, help="Path to a .shortcut file")
    parser.add_argument(
        "--facts",
        type=Path,
        default=FACTS,
        help="Path to jellycore_facts.json",
    )
    args = parser.parse_args()

    facts = json.loads(args.facts.read_text())
    jellycore_idents = {a["identifier"] for a in facts["actions"]}
    structural_idents = set(facts.get("structural_identifiers", []))
    all_known = jellycore_idents | structural_idents

    decoded = decode_file(args.sample)
    actions = decoded.workflow.get("WFWorkflowActions") or []
    counter: Counter[str] = Counter(
        a["WFWorkflowActionIdentifier"]
        for a in actions
        if isinstance(a, dict) and isinstance(a.get("WFWorkflowActionIdentifier"), str)
    )

    sample_idents = set(counter)
    covered_actions = sample_idents & jellycore_idents
    covered_structural = sample_idents & structural_idents
    covered = covered_actions | covered_structural
    missing = sample_idents - all_known

    third_party = {i for i in missing if not i.startswith("is.workflow.actions.")}
    first_party_missing = missing - third_party

    out = DOC_DIR / f"coverage_{args.sample.stem}.md"
    out.write_text(
        _render(args.sample, counter, covered, first_party_missing, third_party)
    )

    print(f"sample:          {args.sample.name}")
    print(f"  total actions: {len(actions)}")
    print(f"  distinct ids:  {len(sample_idents)}")
    print(
        f"  covered by Jellycore:    {len(covered):>4} ({_pct(covered, sample_idents)})"
    )
    print(f"    via lookup table:      {len(covered_actions):>4}")
    print(f"    via language struct:   {len(covered_structural):>4}")
    print(f"  missing (first-party):   {len(first_party_missing):>4}")
    print(f"  missing (third-party):   {len(third_party):>4}")
    print(f"wrote {out.relative_to(Path.cwd())}")
    return 0


def _pct(numer: set[str] | list[str], denom: set[str] | list[str]) -> str:
    return f"{100 * len(numer) / len(denom):.0f}%" if denom else "—"


def _render(
    sample: Path,
    counter: Counter[str],
    covered: set[str],
    missing_first: set[str],
    missing_third: set[str],
) -> str:
    lines = [
        f"# Coverage: `{sample.name}` vs Jellycore",
        "",
        "Auto-generated by `scripts/coverage_report.py`. Compares the action "
        "identifiers in this sample against the [Open-Jellycore](https://github.com/OpenJelly/Open-Jellycore) "
        "fact dataset (`data/jellycore_facts.json`).",
        "",
        f"**Distinct identifiers in sample:** {len(counter)}",
        f"**Covered by Jellycore:** {len(covered)} ({_pct(covered, set(counter))})",
        "",
        "## Missing first-party identifiers (`is.workflow.actions.*`)",
        "",
        "Actions Apple ships that Jellycore doesn't model. These are likely "
        "post-2023 additions to Shortcuts (Jellycore's last commit cadence has slowed).",
        "",
    ]
    if missing_first:
        lines += ["| count | identifier |", "|------:|------------|"]
        lines.extend(
            f"| {counter[ident]} | `{ident}` |"
            for ident in sorted(missing_first, key=lambda i: -counter[i])
        )
    else:
        lines.append("_None._")

    lines += [
        "",
        "## Missing third-party identifiers",
        "",
        "Actions exposed by other apps' AppIntents (Notes, Mail, third-party apps). "
        "Some of these are covered by Jellycore's other `Apps/*/Actions/` lookup tables; "
        "we only loaded the first-party `Shortcuts` table here.",
        "",
    ]
    if missing_third:
        lines += ["| count | identifier |", "|------:|------------|"]
        lines.extend(
            f"| {counter[ident]} | `{ident}` |"
            for ident in sorted(missing_third, key=lambda i: -counter[i])
        )
    else:
        lines.append("_None._")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
