"""Decode every `.shortcut` in `samples/` (incl. `private/`) for inspection.

Produces:
  samples/decoded/<name>.xml      — full XML plist (lossless round-trip target)
  samples/decoded/<name>.summary  — action breakdown
  docs/known_identifiers.md       — identifier histogram across all samples

Run from repo root:  uv run python scripts/decode_all.py
"""

from __future__ import annotations

import plistlib
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Ensure src/ is importable when run as a script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from shortcut_lib.decode import decode_file

REPO = Path(__file__).resolve().parent.parent
SAMPLES = REPO / "samples"
DECODED = SAMPLES / "decoded"
DOC = REPO / "docs" / "known_identifiers.md"


def main() -> None:
    DECODED.mkdir(exist_ok=True)
    sources = sorted(SAMPLES.glob("*.shortcut")) + sorted(
        (SAMPLES / "private").glob("*.shortcut")
    )

    histogram: Counter[str] = Counter()
    by_identifier: dict[str, set[str]] = defaultdict(set)
    by_sample: list[tuple[str, int, int]] = []  # (name, total, distinct)

    for src in sources:
        decoded = decode_file(src)
        is_private = src.parent.name == "private"
        out_stem = ("private/" if is_private else "") + src.stem
        out_xml = DECODED / f"{out_stem}.xml"
        out_xml.parent.mkdir(parents=True, exist_ok=True)
        out_xml.write_bytes(plistlib.dumps(decoded.workflow, fmt=plistlib.FMT_XML))

        actions = decoded.workflow.get("WFWorkflowActions") or []
        local_counter: Counter[str] = Counter(
            a["WFWorkflowActionIdentifier"]
            for a in actions
            if isinstance(a, dict)
            and isinstance(a.get("WFWorkflowActionIdentifier"), str)
        )
        histogram.update(local_counter)
        for ident in local_counter:
            by_identifier[ident].add(src.stem)
        by_sample.append((out_stem, len(actions), len(local_counter)))

    _write_doc(histogram, by_identifier, by_sample)
    _print_summary(histogram, by_sample)


def _write_doc(
    histogram: Counter[str],
    by_identifier: dict[str, set[str]],
    by_sample: list[tuple[str, int, int]],
) -> None:
    lines = [
        "# Known action identifiers",
        "",
        "Auto-generated by `scripts/decode_all.py` from the local sample set.",
        "Histogram of every `WFWorkflowActionIdentifier` seen across "
        f"{len(by_sample)} decoded shortcuts. Use this to prioritise schema "
        "coverage — start with the most-used identifiers, since each one we "
        "model unlocks a real shortcut for round-trip testing.",
        "",
        "## Frequency",
        "",
        "| count | identifier | seen in |",
        "|------:|------------|---------|",
    ]
    for ident, count in histogram.most_common():
        samples = ", ".join(sorted(by_identifier[ident]))
        lines.append(f"| {count} | `{ident}` | {samples} |")

    lines += [
        "",
        "## Per-sample breakdown",
        "",
        "| sample | total actions | distinct identifiers |",
        "|--------|--------------:|---------------------:|",
    ]
    for name, total, distinct in by_sample:
        lines.append(f"| `{name}` | {total} | {distinct} |")

    DOC.write_text("\n".join(lines) + "\n")


def _print_summary(
    histogram: Counter[str], by_sample: list[tuple[str, int, int]]
) -> None:
    print(f"decoded {len(by_sample)} shortcuts")
    print(f"  total actions:        {sum(t for _, t, _ in by_sample)}")
    print(f"  distinct identifiers: {len(histogram)}")
    print()
    print("top 15 identifiers:")
    for ident, count in histogram.most_common(15):
        print(f"  {count:3d}  {ident}")


if __name__ == "__main__":
    main()
